export const SETTINGS_LAUNCH_ROUTE_KEY: string = 'settings.launchRoute';
export const SETTINGS_LAUNCH_PARAM_ROUTE: string = 'settingsRoute';

export const ROUTE_SETTINGS_HOME: string = '';
export const ROUTE_LAYOUT_DISPLAY: string = 'layout_display';
export const ROUTE_KEY_EFFECT: string = 'key_effect';
export const ROUTE_TOOLBAR: string = 'toolbar';
export const ROUTE_ASSIST_INPUT: string = 'assist_input';
export const ROUTE_KEYBOARD_MANAGE: string = 'keyboard_manage';
export const ROUTE_SPEECH_TEXT: string = 'speech_text';
export const ROUTE_SKIN: string = 'skin';
export const ROUTE_DICTIONARY: string = 'dictionary';
export const ROUTE_SYSTEM_MATERIAL: string = 'system_material';
export const ROUTE_ABOUT: string = 'about';
export const ROUTE_HELP: string = 'help';
